api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GradStatusServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

More junits are added for coverage.

More junits are added for coverage.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/GradCommonConfig.java
api/src/main/java/ca/bc/gov/educ/api/graduation/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/graduation/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/LogHelper.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml
tools/openshift/api.dc.yaml

Splunk logging feature is newly added.

Splunk logging feature is newly added.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradStatusService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/OptionalProgramService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/ThreadLocalStateUtil.java

correlationID is delegated to the downstream api calls.

correlationID is delegated to the downstream api calls.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

In progress course not showing on XML

GRAD2-1342

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java

GRAD2-1559

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/GraduateStudentProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/TokenUtils.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

GRAD2-1655: bug fixes on generating school reports for many schools.

GRAD2-1655: bug fixes on generating school reports for many schools.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GradStudentTranscripts.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/AlgorithmSupport.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/GraduateStudentProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksReportsProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

[GRAD2-1643](https://gww.jira.educ.gov.bc.ca/browse/GRAD2-1643)
Student has graduated from a public school - credentials create - changed their School of Record to an independent school and ran Reports Only - issues

GRAD2-1643

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/StudentAssessmentDuplicatesWrapper.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

User runs graduation algorithm from the student Grad status page and updates students' data - audit record not showing IDIR

GRAD2-1669

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksRegistrationsProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

Student Demographic Json change for STS

GRAD2-1716

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GradAlgorithmGraduationStudentRecord.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GradSearchStudent.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GraduationStudentRecord.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

GRAD2-1683

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GraduationStudentRecord.java

GRADT-525: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/GraduationData.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/StudentCourse.java

Add Latest Session Date to student "CLOB"

GRAD2-1770

---

api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/ReportOptions.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/GraduationControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

Add Info message to XML preview jasper report

GRAD2-1725

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/AlgorithmSupport.java

GRAD2-1778 : the task is complete

GRAD2-1778 : the task is complete

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

Comment out FIP and PFD from programCodes in json

GRAD2-1772

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/ResponseHelper.java
api/src/main/resources/application.yaml

Performed Refactoring/Linting Grad Graduation Api

GRAD2-1929 Refactoring/Linting

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java

GRAD2-1978

---

api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/GraduationControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/SchooReportsServiceTest.java

Year-End Disribution run (DISTRUN_YE) - reports School-Level (DISTREP_YE_SC) and District-Level (DISTREP_YE_SD)

GRAD2-1850

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/ReportRequest.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/GraduationControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/SchooReportsServiceTest.java
api/src/test/resources/application.yaml

Grad release 1.8.30

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/Student.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/TranscriptCourse.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

Done with PSIRUN generation of flat files for FTP transmission mode

Grad2-1931 Distribution PSI FTP

---

api/pom.xml

Grad release 1.1.0

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

GRAD2-2102: task is completed.

GRAD2-2102: task is completed.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

Grad release 1.1.1

---

api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/AlgorithmSupport.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/GraduationControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

GRAD2-2091: task is complete

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

GRAD2-2142: Fixed the missing nonGradReasons for SCCP with future date.

GRAD2-2142: Fixed the missing nonGradReasons for SCCP with future date.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/EducGraduationApplicationConfig.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/RESTServiceGETTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

Reinstate Academic Award Program PFD and FIP for XML for July 1

GRAD2-2133

---

api/src/main/java/ca/bc/gov/educ/api/graduation/util/StudentAssessmentDuplicatesWrapper.java

GRAD2-2158: bug fix on duplicate check for student assessment to make it working for pseudo assessment created by equivalency rule.

GRAD2-2158: bug fix on duplicate check for student assessment.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/StudentCourse.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/Mark.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/TranscriptCourse.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

PSI FTP >DAT files changes are done.

Grad2-2182 PSI FTP .DAT file changes required

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/TranscriptCourse.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

Non grad reasons, reqt type, localid, special case are fixed.

Grad-2205 Non grad reasons 

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/GraduateStudentProcess.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

User runs graduation algorithm from the student Grad status page and updates students' data - audit record now showing IDIR

Grad2-1669 Audit record now showing IDIR

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/GraduateStudentProcess.java

Removed audit history duplicate entry for updates.

Grad2-1669 Audit history Showing IDIR for updates

---

api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksReportsProcess.java

GRAD2-2074: the issue is resolved.

GRAD2-2074: the issue is resolved.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/GradLocalDateDeserializer.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/GradLocalDateTimeSerializer.java

GRAD2-2252: task is completed.

GRAD2-2252: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/controller/EdwSnapshotController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/EdwGraduationSnapshot.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/StudentNonGradReason.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/AlgorithmProcessFactory.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/EdwSnapshotService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/EdwSnapshotControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/EdwSnapshotServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmServiceTest.java
api/src/test/resources/application.yaml

GRAD2-2325: hypothetical grad algorithm support is added.

GRAD2-2325: hypothetical grad algorithm support is added.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/report/GraduationStatus.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java

HD-22855 Year-End Graduation Run - Distribution Report Counts Error

GRAD2-2339-2

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java

HD-23020-P3 - GRAD - Service Request - Locally Developed Courses on 2023 Transcripts Missing Parenthesis

GRAD2-2392

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/RestWebClient.java

Unexpected Internal Server Error for TVRs for Projected Non-Grads

GRAD2-2408

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

GRAD2-2319: task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

(GRAD) - P3 Incident: 1950 program includes Non-Completion Reason "506 - N/A"

GRAD2-2477

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/EdwSnapshotService.java

GRAD2-2458: task is complete.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/config/GradCommonConfig.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/ResponseObjCache.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/TokenUtils.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/SchooReportsServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/TokenUtilsTest.java
api/src/test/resources/json/studentSchoolYearEndResponse.json

HD-22859 (GRAD) YE Distribution run should direct Certificates to School at Graduation, not School of Record

GRAD2-2377

---

api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/resources/application.yaml
api/src/test/resources/application.yaml

Done with endpoint replacements

Grad2-2632 school api call is replaced with trax api.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

GRAD2-2724: task is complete.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradStatusService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/RESTService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/GradLocalDateTimeSerializer.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/resources/application.yaml

HD-21698 (GRAD) Distribution reports in the YE Distribution are randomly picking up Independent Schools

GRAD2-2315

---

.github/workflows/build.from.developer.branch.deploy.to.dev.yml
.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml
.github/workflows/create_tag.yml
.github/workflows/deploy_prod.yml
.github/workflows/deploy_test.yml
.github/workflows/on.pr.yml
api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/resources/application.yaml

A patch was done on main. Updating release branch to reflect changes.

Updating release branch for patch

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/service/RESTService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java

After testing the hotfix patch on TEST env, applying hotfix code changes to grad-release to keep them in synch.

Applying hotfix to grad release 

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/RestWebClient.java
api/src/main/java/ca/bc/gov/educ/api/graduation/controller/EdwSnapshotController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/controller/GraduationController.java
api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/ProcessorData.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/AlgorithmSupport.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/GraduateStudentProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksRegistrationsProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/process/ProjectedGradFinalMarksReportsProcess.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/EdwSnapshotService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GradStatusService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/OptionalProgramService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/ReportService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolReportsService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/SchoolService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/JsonTransformer.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/TokenUtils.java
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/EdwSnapshotControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/controller/GraduationControllerTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/EdwSnapshotServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GradAlgorithmServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GradStatusServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/OptionalProgramServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/SchooReportsServiceTest.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/SchoolServiceTest.java

GRAD2-2929: task is completed.

GRAD2-2929: task is completed.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/resources/application.yaml
api/src/test/java/ca/bc/gov/educ/api/graduation/service/ReportServiceTest.java
api/src/test/resources/application.yaml

GRAD2-2951: task is complete.

---

api/src/main/java/ca/bc/gov/educ/api/graduation/config/RequestInterceptor.java
api/src/main/java/ca/bc/gov/educ/api/graduation/service/RESTService.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/EducGraduationApiConstants.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/JwtUtil.java
api/src/main/java/ca/bc/gov/educ/api/graduation/util/ThreadLocalStateUtil.java

GRAD2-3012: task is complete.

---

.github/dependabot.yml
.github/workflows/build.from.developer.branch.deploy.to.dev.yml
.github/workflows/build.from.main.branch.deploy.to.dev.yml
.github/workflows/build.from.release.branch.deploy.to.dev.yml

Grad2-3131 ZAPscan verson upgraded

---

api/src/main/java/ca/bc/gov/educ/api/graduation/model/dto/School.java

GRAD2-2761: districtId is newly added into School Clob.

GRAD2-2761: districtId is newly added into School Clob.

---

api/pom.xml
api/src/main/java/ca/bc/gov/educ/api/graduation/config/WebSecurityConfiguration.java
api/src/main/java/ca/bc/gov/educ/api/graduation/controller/APIMetadataController.java

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

GRAD2-3335 - Add Metadata Endpoint to All GRAD APIs

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/GraduationService.java
api/src/test/java/ca/bc/gov/educ/api/graduation/service/GraduationServiceTest.java

GRAD2-3348 - Splunk alerts showing school GUID instead of Mincode

GRAD2-3348 - Splunk alerts showing school GUID instead of Mincode

---

api/src/main/java/ca/bc/gov/educ/api/graduation/service/DistrictReportService.java

Grad2-3416 District Label Info for YE corrected
